# Generated by Django 3.2.12 on 2022-03-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_pricing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing',
            field=models.ManyToManyField(blank=True, to='content.Pricing'),
        ),
    ]
